# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

byproducts <- function(num_obs, K, NSbj, C_star_sbj, gamma, X_sbj, beta, Z_sbj, L_sbj, Psi, Psi0, ID, Clusters, active, flatten_gamma) {
    .Call('_cvarpyp_byproducts', PACKAGE = 'cvarpyp', num_obs, K, NSbj, C_star_sbj, gamma, X_sbj, beta, Z_sbj, L_sbj, Psi, Psi0, ID, Clusters, active, flatten_gamma)
}

KnotSelection <- function(small_k, NSbj, tau, C_star_sbj, prsd_gamma, Inv_middle, X_sbj, beta, L_sbj, ID, Clusters) {
    .Call('_cvarpyp_KnotSelection', PACKAGE = 'cvarpyp', small_k, NSbj, tau, C_star_sbj, prsd_gamma, Inv_middle, X_sbj, beta, L_sbj, ID, Clusters)
}

MakeRk <- function(K, tau, active, C_star_sbj, inv_middle, inv_middle0, gamma, NSbj, flatten_gamma) {
    .Call('_cvarpyp_MakeRk', PACKAGE = 'cvarpyp', K, tau, active, C_star_sbj, inv_middle, inv_middle0, gamma, NSbj, flatten_gamma)
}

sample_randomeffects <- function(n, Zi, InvAdj, Li, C_star_sbj, gamma, X_sbj, beta, Psi, theta_k, Clusters, r, flatten_gamma) {
    .Call('_cvarpyp_sample_randomeffects', PACKAGE = 'cvarpyp', n, Zi, InvAdj, Li, C_star_sbj, gamma, X_sbj, beta, Psi, theta_k, Clusters, r, flatten_gamma)
}

MakeRkPsi <- function(n_obs, K, Rk, tau, active, C_star_sbj, Z_sbj, p_Psi, gamma, theta_k, NSbj, flatten_gamma) {
    .Call('_cvarpyp_MakeRkPsi', PACKAGE = 'cvarpyp', n_obs, K, Rk, tau, active, C_star_sbj, Z_sbj, p_Psi, gamma, theta_k, NSbj, flatten_gamma)
}

ObtainOutput <- function(NSbj, K, Diri_p, L_sbj, C_star_sbj, X_sbj, beta, Z_sbj, bi, gamma, theta_k, flatten_gamma) {
    .Call('_cvarpyp_ObtainOutput', PACKAGE = 'cvarpyp', NSbj, K, Diri_p, L_sbj, C_star_sbj, X_sbj, beta, Z_sbj, bi, gamma, theta_k, flatten_gamma)
}

