# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

byproducts <- function(num_obs, K, NSbj, C_star_sbj, gamma, X_sbj, beta, Z_sbj, L_sbj, Psi, ID, Clusters, active, flatten_gamma) {
    .Call('_fvcc_byproducts', PACKAGE = 'fvcc', num_obs, K, NSbj, C_star_sbj, gamma, X_sbj, beta, Z_sbj, L_sbj, Psi, ID, Clusters, active, flatten_gamma)
}

KnotSelection <- function(small_k, NSbj, tau, C_star_sbj, prsd_gamma, Inv_middle, X_sbj, beta, L_sbj, ID, Clusters) {
    .Call('_fvcc_KnotSelection', PACKAGE = 'fvcc', small_k, NSbj, tau, C_star_sbj, prsd_gamma, Inv_middle, X_sbj, beta, L_sbj, ID, Clusters)
}

MakeRk <- function(K, tau, active, C_star_sbj, gamma, NSbj, flatten_gamma) {
    .Call('_fvcc_MakeRk', PACKAGE = 'fvcc', K, tau, active, C_star_sbj, gamma, NSbj, flatten_gamma)
}

sample_randomeffects <- function(n, Zi, InvAdj, Li, C_star_sbj, gamma, X_sbj, beta, Psi, theta_k, Clusters, r, flatten_gamma) {
    .Call('_fvcc_sample_randomeffects', PACKAGE = 'fvcc', n, Zi, InvAdj, Li, C_star_sbj, gamma, X_sbj, beta, Psi, theta_k, Clusters, r, flatten_gamma)
}

ObtainOutput <- function(NSbj, K, Diri_p, L_sbj, C_star_sbj, X_sbj, beta, Z_sbj, bi, gamma, theta_k, flatten_gamma) {
    .Call('_fvcc_ObtainOutput', PACKAGE = 'fvcc', NSbj, K, Diri_p, L_sbj, C_star_sbj, X_sbj, beta, Z_sbj, bi, gamma, theta_k, flatten_gamma)
}

